development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # database: backend_test
      # hosts:
        # - localhost:27017
      uri: "mongodb+srv://antcamp23:<PASSWORD>@cluster0.ejwx2sq.mongodb.net/backend_development"
  # Configure Mongoid specific options. (optional)
  options:
    
test:
  clients:
    default:
      # database: backend_test
      # hosts:
        # - localhost:27017
      uri: "mongodb+srv://antcamp23:<PASSWORD>@cluster0.ejwx2sq.mongodb.net/backend_test"
      options:

